### ISSUE TITLE
maxCacheSize

### ISSUE THREAD

**Issue by WillSquire** [graphql/dataloader#194]
This is partially a query and partially a feature request (depending on if it's already existing). I wondered if it's possible to set `maxCacheSize` or something equivalent in dataloader's config options? As I understand it, it can consume infinite memory 'as-is' and sounds a bit like a venrability that could be exploited. 

Had a little gander at https://github.com/graphql/dataloader/issues/56 and saw a suggested library, but I wondered if something existed in the library already to avoid anything as heavy as importing something else (a bit like the `maxBatchSize` option).

**Comment by leebyron** [comment]
Unfortunately this isn't a straight-forward thing to do since cache invalidation behavior can be very opinionated and product specific, and also heavy on byte-weight since the implementation can be complex. DataLoader's most common case is for a per-request cache when an infinitely growing cache is the appropriate choice (since it will be discarded after the short lifespan of the request)

However in some cases, I know people want to use DataLoader for long-lived caches. In that case, you might want to look at something like an LRU cache or a time-expiry cache. Something like http://www.collectionsjs.com/lru-map would probably suffice.
